# Copyright 2020-2023 the .NET Foundation
# Licensed under the MIT License

parameters:
- name: isMainDev
  type: boolean
  default: false
- name: isRelease
  type: boolean
  default: false

jobs:

# TODO: flesh out our usual deployment processes (GitHub Releases, npmjs.org, Zenodo, etc.)

# Deployment jobs that should only happen on updates to the main branch.

- ${{ if parameters.isMainDev }}:
  # Currently (2023 October) we're deploying to prod from the main branch, since
  # we're launching the service and will want to iterate rapidly. And we're
  # probably going to tear down the dev environment unless we find a way to make
  # it much cheaper to run. But ideally we'd deploy to a dev environment and
  # only push to prod in Cranko releases, or whatever.

  - job: deploy_prod
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Deployment Credentials
    steps:
    - template: azure-job-setup.yml

    # Custom startup command needed to work around module-loading issue related
    # to disappearance of symlinks in the Zip-based package
    - task: AzureWebApp@1
      displayName: Deploy app to prod environment
      inputs:
        azureSubscription: 'aas@wwtadmindotnetfoundation'
        appType: webAppLinux
        appName: wwtprod-cxfe
        runtimeStack: 'NODE|18-lts'
        package: $(Pipeline.Workspace)/app-package/app-package-$(Build.BuildId).zip
        startUpCommand: node node_modules/nuxt/bin/nuxt.mjs start

# Deployment jobs that should only happen on updates to `rc`, i.e.
# primary releases.

- ${{ if parameters.isRelease }}:
  - job: branch_and_tag
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Deployment Credentials
    steps:
    - template: azure-job-setup.yml
      parameters:
        setupGit: true
    - bash: |
        set -xeou pipefail
        cranko release-workflow tag
        git push --tags origin release:release
      displayName: Tag and push
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)

  # TODO: the rest of the usual stuff
