# Copyright 2020-2023 the .NET Foundation
# Licensed under the MIT License

trigger:
  branches:
    include:
    - master
    - rc

stages:
- stage: Package
  jobs:
  - template: azure-packaging.yml

# We should probably end up with some testing-type steps here that run on all
# builds! But right now there's nothing more to do.

- stage: Deploy
  condition: and(succeeded('Package'), ne(variables['build.reason'], 'PullRequest'))
  jobs:
  - template: azure-deployment.yml
    parameters:
      isMainDev: ${{ ne(variables['Build.SourceBranchName'], 'rc') }}
      isRelease: ${{ eq(variables['Build.SourceBranchName'], 'rc') }}
